#!/usr/bin/env python3
"""Regenerate languages/sleek-audio-player.pot from the PHP sources.

Usage:  python tools/make-pot.py
Needs:  nothing beyond the Python standard library

The .pot is a build output, exactly like *.min.js and *.mo: it is generated,
never hand-edited. Keeping it hand-written is how strings silently go missing
from translations - the string exists in the code, the translator never sees
it, and the site shows English.

CI runs this script and fails if the committed .pot differs (see ci.yml), so a
new __() call in PHP cannot reach a release without its .pot entry.

Note: strings shown by assets/js/player.js are NOT extracted from the JS. They
are defined once in the PHP i18n array in includes/class-player.php and handed
to the script via wp_localize_script(), so extracting the PHP covers them.
"""
import re
import sys
from datetime import datetime, timezone
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
LANG_DIR = ROOT / "languages"
POT_PATH = LANG_DIR / "sleek-audio-player.pot"
DOMAIN = "sleek-audio-player"

# Files scanned, in the order their strings appear in the .pot
#
# block.js is included because the Gutenberg block calls wp.i18n.__() directly
# rather than receiving its strings from PHP. Without it those labels would be
# marked up as translatable and still never reach a translator - which is
# exactly how they stayed English until 2.11.0. Its translations are delivered
# as .json (see tools/make-json.py), not through the .mo.
SOURCES = [
    "sleek-audio-player.php",
    "includes/class-player.php",
    "includes/class-theme-manager.php",
    "includes/class-waveform-manager.php",
    "uninstall.php",
    "assets/js/block.js",
]

# A single-quoted PHP string, allowing \' escapes
SQ = r"'((?:[^'\\]|\\.)*)'"

SINGULAR_RE = re.compile(
    r"\b(?:esc_html__|esc_attr__|esc_html_e|esc_attr_e|__|_e)\(\s*"
    + SQ
    + r"\s*,\s*'" + re.escape(DOMAIN) + r"'\s*\)"
)
PLURAL_RE = re.compile(
    r"\b_n\(\s*" + SQ + r"\s*,\s*" + SQ + r"\s*,.*?,\s*'" + re.escape(DOMAIN) + r"'\s*\)"
)
TRANSLATORS_RE = re.compile(r"/\*\s*(translators:.*?)\*/", re.S)


def php_unescape(text):
    """Turn a PHP single-quoted literal into its runtime value."""
    return text.replace("\\'", "'").replace("\\\\", "\\")


def po_escape(text):
    return text.replace("\\", "\\\\").replace('"', '\\"')


def translator_comment(source, match_start):
    """The /* translators: */ comment that belongs to this call, if any.

    gettext associates a comment with the call that follows it, so only a
    comment with no other translatable call in between counts.
    """
    best = None
    for c in TRANSLATORS_RE.finditer(source, 0, match_start):
        best = c
    if not best:
        return None
    between = source[best.end():match_start]
    if SINGULAR_RE.search(between) or PLURAL_RE.search(between):
        return None
    return " ".join(best.group(1).split())


def extract():
    """All translatable strings, keyed by (msgid, msgid_plural)."""
    entries = {}

    def add(key, rel_path, line, comment):
        entry = entries.setdefault(key, {"refs": [], "comment": None})
        ref = f"{rel_path}:{line}"
        if ref not in entry["refs"]:
            entry["refs"].append(ref)
        if comment and not entry["comment"]:
            entry["comment"] = comment

    for rel_path in SOURCES:
        path = ROOT / rel_path
        if not path.exists():
            sys.exit(f"make-pot: source file missing: {rel_path}")
        source = path.read_text(encoding="utf-8")

        for m in SINGULAR_RE.finditer(source):
            line = source.count("\n", 0, m.start()) + 1
            add((php_unescape(m.group(1)), None), rel_path, line,
                translator_comment(source, m.start()))

        for m in PLURAL_RE.finditer(source):
            line = source.count("\n", 0, m.start()) + 1
            add((php_unescape(m.group(1)), php_unescape(m.group(2))), rel_path, line,
                translator_comment(source, m.start()))

    return entries


def plugin_version():
    header = (ROOT / "sleek-audio-player.php").read_text(encoding="utf-8")
    m = re.search(r"^\s*\*\s*Version:\s*(\S+)", header, re.M)
    return m.group(1) if m else "unknown"


def render(entries):
    stamp = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M+0000")
    out = [
        "# Copyright (C) 2026 Martin Gräbing",
        "# This file is distributed under the GPL v2 or later.",
        "# Generated by tools/make-pot.py - do not edit by hand.",
        'msgid ""',
        'msgstr ""',
        f'"Project-Id-Version: Sleek Audio Player {plugin_version()}\\n"',
        '"Report-Msgid-Bugs-To: https://www.duesseldorp.de\\n"',
        f'"POT-Creation-Date: {stamp}\\n"',
        '"MIME-Version: 1.0\\n"',
        '"Content-Type: text/plain; charset=UTF-8\\n"',
        '"Content-Transfer-Encoding: 8bit\\n"',
        '"PO-Revision-Date: YEAR-MO-DA HO:MI+ZONE\\n"',
        '"Last-Translator: FULL NAME <EMAIL@ADDRESS>\\n"',
        '"Language-Team: LANGUAGE <LL@li.org>\\n"',
        '"Language: \\n"',
        '"Plural-Forms: nplurals=2; plural=(n != 1);\\n"',
        "",
    ]

    for (msgid, plural), data in entries.items():
        if data["comment"]:
            out.append(f"#. {data['comment']}")
        out.append("#: " + " ".join(data["refs"]))
        out.append(f'msgid "{po_escape(msgid)}"')
        if plural is None:
            out.append('msgstr ""')
        else:
            out.append(f'msgid_plural "{po_escape(plural)}"')
            out.append('msgstr[0] ""')
            out.append('msgstr[1] ""')
        out.append("")

    return "\n".join(out)


def main():
    check_only = "--check" in sys.argv
    entries = extract()
    new = render(entries)

    if check_only:
        if not POT_PATH.exists():
            sys.exit("make-pot --check: languages/sleek-audio-player.pot is missing")
        old = POT_PATH.read_text(encoding="utf-8")
        # The creation timestamp changes on every run; it is not a content change.
        strip = lambda t: [l for l in t.splitlines() if not l.startswith('"POT-Creation-Date')]
        if strip(old) != strip(new):
            old_ids = set(re.findall(r'^msgid "(.+)"$', old, re.M))
            new_ids = set(re.findall(r'^msgid "(.+)"$', new, re.M))
            for missing in sorted(new_ids - old_ids):
                print(f"  fehlt in der .pot: {missing}")
            for stale in sorted(old_ids - new_ids):
                print(f"  nicht mehr im Code: {stale}")
            sys.exit("make-pot --check: languages/sleek-audio-player.pot is out of date - run: python tools/make-pot.py")
        print(f"pot is in sync ({len(entries)} strings)")
        return

    POT_PATH.write_text(new, encoding="utf-8")
    print(f"wrote {POT_PATH.relative_to(ROOT)} ({len(entries)} strings)")


if __name__ == "__main__":
    main()
